pipeline {
    agent none
    stages {
     stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
      steps {
         stage('Build') {
            steps {
                // Build the project using Maven
                sh 'mvn clean install'
            }
        }
      }
      steps {  
         stage('Test') {
            steps {
                // Run unit tests
                sh 'mvn test'
            }
        }
    }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
         sh 'mkdir abc'
      }
    }
}
}
