pipeline {
    agent {
    docker { image 'node:16-alpine' }
    }
    stages {
     stage('Checkout') {
      steps {
        sh 'echo passed'
        //git branch: 'main', url: 'https://github.com/avinashreddy023/SaiJavaCode'
      }
    }
    stage('Build and Test') {
        agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
       }
       steps {
         sh 'mvn clean install'
         sh 'mvn test'
         sh 'mvn package'
      }
    }
    }
}
         
