pipeline {
    agent none
    stages {
     stage('Checkout') {
      steps {
        sh 'echo passed'
        //git branch: 'main', url: 'https://github.com/avinashreddy023/SaiJavaCode'
      }
    }
    stage('Build and Test') {
      steps {
        sh 'ls -ltr'
        // build the project and create a JAR file
        sh 'cd home && mvn clean package'
      }
    }
    }
}
         
